export const GERMAN_CITIES = [
  "Berlin",
  "Hamburg",
  "München",
  "Köln",
  "Frankfurt",
  "Stuttgart",
  "Düsseldorf",
  "Dortmund",
  "Essen",
  "Leipzig",
  "Bremen",
  "Dresden",
  "Hannover",
  "Nürnberg",
  "Duisburg",
  "Bochum",
  "Wuppertal",
  "Bielefeld",
  "Bonn",
  "Mannheim",
  "Karlsruhe",
  "Wiesbaden",
  "Münster",
  "Gelsenkirchen",
  "Aachen",
  "Braunschweig",
  "Chemnitz",
  "Kiel",
  "Halle",
  "Magdeburg",
] as const;

export type GermanCity = (typeof GERMAN_CITIES)[number];
